SELECT
    C.TABLE_NAME,
    C.COLUMN_NAME,
    C.DATA_TYPE,
    C.CHARACTER_MAXIMUM_LENGTH,
    CASE 
        WHEN TC.CONSTRAINT_TYPE = 'PRIMARY KEY' THEN 'PRIMARY KEY'
        WHEN TC.CONSTRAINT_TYPE = 'FOREIGN KEY' THEN 'FOREIGN KEY'
        ELSE NULL
    END AS KEY_TYPE,
    CASE 
        WHEN EXISTS (
            SELECT 1
            FROM sys.tables T
            JOIN sys.columns SC ON T.object_id = SC.object_id AND SC.name = C.COLUMN_NAME
            JOIN sys.index_columns IC ON SC.object_id = IC.object_id AND SC.column_id = IC.column_id
            WHERE T.name = C.TABLE_NAME
        ) THEN 'TRUE'
        ELSE 'FALSE'
    END AS IS_INDEXED
FROM INFORMATION_SCHEMA.COLUMNS C
LEFT JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE KU
    ON C.TABLE_NAME = KU.TABLE_NAME AND C.COLUMN_NAME = KU.COLUMN_NAME
LEFT JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS TC
    ON KU.CONSTRAINT_NAME = TC.CONSTRAINT_NAME
ORDER BY C.TABLE_NAME, C.ORDINAL_POSITION;